/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HtwTopMenu {
        /**
          * use dark mode if true
         */
        "dark": boolean;
    }
}
declare global {
    interface HTMLHtwTopMenuElement extends Components.HtwTopMenu, HTMLStencilElement {
    }
    var HTMLHtwTopMenuElement: {
        prototype: HTMLHtwTopMenuElement;
        new (): HTMLHtwTopMenuElement;
    };
    interface HTMLElementTagNameMap {
        "htw-top-menu": HTMLHtwTopMenuElement;
    }
}
declare namespace LocalJSX {
    interface HtwTopMenu {
        /**
          * use dark mode if true
         */
        "dark"?: boolean;
    }
    interface IntrinsicElements {
        "htw-top-menu": HtwTopMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "htw-top-menu": LocalJSX.HtwTopMenu & JSXBase.HTMLAttributes<HTMLHtwTopMenuElement>;
        }
    }
}
